<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Valentine Confession</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #fff0f5;
      color: #333;
      margin: 0;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      overflow: hidden;
    }

    .click-text {
      font-size: 1.2rem;
      margin-bottom: 1rem;
      color: black; /* Changed to black */
      font-weight: bold;
      text-align: center;
    }

    .heart-container {
      text-align: center;
      cursor: pointer;
      animation: pulse 1.5s infinite;
      font-size: 5rem;
      transition: transform 0.3s ease;
      color: #d63384;
    }

    .letter {
      display: none;
      max-width: 700px;
      padding: 2rem;
      background: white;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      border-radius: 1rem;
      animation: fadeIn 1s ease forwards;
    }

    h1 {
      text-align: center;
      color: #d63384;
    }

    .signature {
      margin-top: 2rem;
      text-align: right;
      font-style: italic;
      font-weight: bold;
    }

    @keyframes fadeIn {
      from {
        opacity: 0;
        transform: translateY(30px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    @keyframes pulse {
      0% {
        transform: scale(1);
      }
      50% {
        transform: scale(1.1);
      }
      100% {
        transform: scale(1);
      }
    }
  </style>
</head>
<body>
  <div id="heartSection">
    <div class="click-text">Click me!</div>
    <div class="heart-container" onclick="openLetter()">❤️</div>
  </div>

  <div class="letter" id="letter">
    <h1>Dear You,</h1>
    <p>
      I've been keeping this in for a while, but I think Valentine's Day is the perfect time to say it—you’re the reason my days feel brighter.
      Every little moment with you means more than I can put into words. Your smile, your laughter, the way you make everything feel lighter—it all makes my heart race in the best way possible.
    </p>
    <p>
      So, here it is… I like you, a lot. Maybe even love. Would you be my Valentine? No matter your answer, I just wanted you to know how special you are to me.
      You’ve filled my heart with warmth in ways I never expected, and for that, I’m grateful.
      But if you say yes, I promise to make every day feel like Valentine’s Day for you—to cherish you, to make you smile, and to remind you just how much you mean to me.
    </p>
    <div class="signature">From Rion</div>
  </div>

  <script>
    function openLetter() {
      document.getElementById('heartSection').style.display = 'none';
      document.getElementById('letter').style.display = 'block';
    }
  </script>
</body>
</html>
